import { Inter } from "next/font/google";
import "./globals.css";
//import material design
import "bootstrap-material-design/dist/css/bootstrap-material-design.min.css"
//import nav components
import TopNav from "@/components/topnav";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextEcom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TopNav/>
      {children}</body>
    </html>
  );
}
